import json

en_keys = {
  "navPricing": "Pricing",
  "pricingEyebrow": "Pricing",
  "pricingTitle": "Simple Annual Pricing",
  "pricingIntro": "Everything you need to run your digital menu, with transparent pricing and referral rewards.",
  "pricingPlanTitle": "Restaurant Plan",
  "pricingPlanPrice": "300 DT",
  "pricingPlanPeriod": "/year",
  "pricingPlanDesc": "Everything included for one simple price.",
  "pricingPlanFeat1": "Interactive QR Menu",
  "pricingPlanFeat2": "Unlimited Menu Items",
  "pricingPlanFeat3": "Food Images",
  "pricingPlanFeat4": "Menu Categories",
  "pricingPlanFeat5": "Instant Price Updates",
  "pricingPlanFeat6": "Mobile Optimized Design",
  "pricingPlanFeat7": "QR Code Included",
  "pricingPlanFeat8": "WhatsApp Support & Setup",
  "pricingPlanFeat9": "Unlimited Scans",
  "pricingPlanCta": "Contact Us On WhatsApp",
  "pricingRefBadge": "🎉 Save 50 DT",
  "pricingRefTitle": "Referral Discount",
  "pricingRefPrice": "250 DT",
  "pricingRefDesc": "Were you referred by a partner?",
  "pricingRefFeat1": "Full access to all features",
  "pricingRefFeat2": "Same support and setup assistance",
  "pricingRefFeat3": "<strong>50 DT discount</strong> on your first year",
  "pricingRefCta": "Redeem Referral Code",
  "pricingPartnerTitle": "💰 Partner Program",
  "pricingPartnerSubtitle": "Know restaurant owners?",
  "pricingPartnerDesc": "Earn commissions for every restaurant that joins through your referral code.",
  "pricingPartnerRatesTitle": "Commission Rates",
  "pricingPartnerRates1": "1–9 referrals",
  "pricingPartnerRates1Val": "25 DT / ea",
  "pricingPartnerRates2": "10+ referrals",
  "pricingPartnerRates2Val": "50 DT / ea",
  "pricingPartnerExTitle": "Examples",
  "pricingPartnerEx1": "5 referrals = <strong>125 DT</strong>",
  "pricingPartnerEx2": "10 referrals = <strong>500 DT</strong>",
  "pricingPartnerEx3": "20 referrals = <strong>1000 DT</strong>",
  "pricingPartnerCta": "Become A Partner"
}

fr_keys = {
  "navPricing": "Tarification",
  "pricingEyebrow": "Tarifs",
  "pricingTitle": "Tarification Annuelle Simple",
  "pricingIntro": "Tout ce dont vous avez besoin pour votre menu numérique, avec des prix transparents.",
  "pricingPlanTitle": "Plan Restaurant",
  "pricingPlanPrice": "300 DT",
  "pricingPlanPeriod": "/an",
  "pricingPlanDesc": "Tout est inclus pour un prix simple.",
  "pricingPlanFeat1": "Menu QR Interactif",
  "pricingPlanFeat2": "Articles de Menu Illimités",
  "pricingPlanFeat3": "Images de Plats",
  "pricingPlanFeat4": "Catégories de Menu",
  "pricingPlanFeat5": "Mises à jour Instantanées",
  "pricingPlanFeat6": "Design Optimisé Mobile",
  "pricingPlanFeat7": "Code QR Inclus",
  "pricingPlanFeat8": "Support & Configuration WhatsApp",
  "pricingPlanFeat9": "Scans Illimités",
  "pricingPlanCta": "Contactez-nous sur WhatsApp",
  "pricingRefBadge": "🎉 Économisez 50 DT",
  "pricingRefTitle": "Remise de Parrainage",
  "pricingRefPrice": "250 DT",
  "pricingRefDesc": "Avez-vous été recommandé par un partenaire ?",
  "pricingRefFeat1": "Accès complet à toutes les fonctionnalités",
  "pricingRefFeat2": "Même support et aide à la configuration",
  "pricingRefFeat3": "<strong>50 DT de remise</strong> sur votre première année",
  "pricingRefCta": "Utiliser le Code de Parrainage",
  "pricingPartnerTitle": "💰 Programme Partenaire",
  "pricingPartnerSubtitle": "Connaissez-vous des restaurateurs ?",
  "pricingPartnerDesc": "Gagnez des commissions pour chaque restaurant qui nous rejoint avec votre code.",
  "pricingPartnerRatesTitle": "Taux de Commission",
  "pricingPartnerRates1": "1–9 parrainages",
  "pricingPartnerRates1Val": "25 DT / ch",
  "pricingPartnerRates2": "10+ parrainages",
  "pricingPartnerRates2Val": "50 DT / ch",
  "pricingPartnerExTitle": "Exemples",
  "pricingPartnerEx1": "5 parrainages = <strong>125 DT</strong>",
  "pricingPartnerEx2": "10 parrainages = <strong>500 DT</strong>",
  "pricingPartnerEx3": "20 parrainages = <strong>1000 DT</strong>",
  "pricingPartnerCta": "Devenir Partenaire"
}

ar_keys = {
  "navPricing": "الأسعار",
  "pricingEyebrow": "الأسعار",
  "pricingTitle": "أسعار سنوية بسيطة",
  "pricingIntro": "كل ما تحتاجه لإدارة قائمة طعامك الرقمية، بأسعار شفافة ومكافآت الإحالة.",
  "pricingPlanTitle": "خطة المطاعم",
  "pricingPlanPrice": "300 د.ت",
  "pricingPlanPeriod": "/سنة",
  "pricingPlanDesc": "كل شيء مشمول في سعر واحد بسيط.",
  "pricingPlanFeat1": "قائمة QR تفاعلية",
  "pricingPlanFeat2": "عناصر قائمة غير محدودة",
  "pricingPlanFeat3": "صور للأطباق",
  "pricingPlanFeat4": "فئات القائمة",
  "pricingPlanFeat5": "تحديثات أسعار فورية",
  "pricingPlanFeat6": "تصميم متوافق مع الجوال",
  "pricingPlanFeat7": "رمز QR مشمول",
  "pricingPlanFeat8": "دعم وإعداد عبر واتساب",
  "pricingPlanFeat9": "عمليات مسح غير محدودة",
  "pricingPlanCta": "تواصل معنا على واتساب",
  "pricingRefBadge": "🎉 وفر 50 د.ت",
  "pricingRefTitle": "خصم الإحالة",
  "pricingRefPrice": "250 د.ت",
  "pricingRefDesc": "هل تم إحالتك من قبل أحد شركائنا؟",
  "pricingRefFeat1": "وصول كامل لجميع الميزات",
  "pricingRefFeat2": "نفس الدعم والمساعدة في الإعداد",
  "pricingRefFeat3": "<strong>خصم 50 د.ت</strong> على عامك الأول",
  "pricingRefCta": "استرداد رمز الإحالة",
  "pricingPartnerTitle": "💰 برنامج الشركاء",
  "pricingPartnerSubtitle": "هل تعرف أصحاب مطاعم؟",
  "pricingPartnerDesc": "اكسب عمولات عن كل مطعم ينضم من خلال رمز الإحالة الخاص بك.",
  "pricingPartnerRatesTitle": "معدلات العمولة",
  "pricingPartnerRates1": "1–9 إحالات",
  "pricingPartnerRates1Val": "25 د.ت / لكل مطعم",
  "pricingPartnerRates2": "+10 إحالات",
  "pricingPartnerRates2Val": "50 د.ت / لكل مطعم",
  "pricingPartnerExTitle": "أمثلة",
  "pricingPartnerEx1": "5 إحالات = <strong>125 د.ت</strong>",
  "pricingPartnerEx2": "10 إحالات = <strong>500 د.ت</strong>",
  "pricingPartnerEx3": "20 إحالة = <strong>1000 د.ت</strong>",
  "pricingPartnerCta": "أصبح شريكاً"
}

files = [
  ("c:/Users/ASUS/Desktop/menu-qr/src/lib/translations/landing-ui.en.json", en_keys),
  ("c:/Users/ASUS/Desktop/menu-qr/src/lib/translations/landing-ui.fr.json", fr_keys),
  ("c:/Users/ASUS/Desktop/menu-qr/src/lib/translations/landing-ui.ar.json", ar_keys)
]

for filepath, keys in files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    data.update(keys)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("Added translations for pricing section to en, fr, and ar.")
