/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuSlugRouteImport } from './routes/menu/$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardQrRouteImport } from './routes/_authenticated/dashboard.qr'
import { Route as AuthenticatedDashboardProductsRouteImport } from './routes/_authenticated/dashboard.products'
import { Route as AuthenticatedDashboardCategoriesRouteImport } from './routes/_authenticated/dashboard.categories'
import { Route as MenuSlugProductProductIdRouteImport } from './routes/menu/$slug.product.$productId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQrRoute =
  AuthenticatedDashboardQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProductsRoute =
  AuthenticatedDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategoriesRoute =
  AuthenticatedDashboardCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const MenuSlugProductProductIdRoute =
  MenuSlugProductProductIdRouteImport.update({
    id: '/product/$productId',
    path: '/product/$productId',
    getParentRoute: () => MenuSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/menu/$slug': typeof MenuSlugRouteWithChildren
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/dashboard/qr': typeof AuthenticatedDashboardQrRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/menu/$slug/product/$productId': typeof MenuSlugProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/menu/$slug': typeof MenuSlugRouteWithChildren
  '/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/dashboard/qr': typeof AuthenticatedDashboardQrRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/menu/$slug/product/$productId': typeof MenuSlugProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/menu/$slug': typeof MenuSlugRouteWithChildren
  '/_authenticated/dashboard/categories': typeof AuthenticatedDashboardCategoriesRoute
  '/_authenticated/dashboard/products': typeof AuthenticatedDashboardProductsRoute
  '/_authenticated/dashboard/qr': typeof AuthenticatedDashboardQrRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/menu/$slug/product/$productId': typeof MenuSlugProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/onboarding'
    | '/menu/$slug'
    | '/dashboard/categories'
    | '/dashboard/products'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/menu/$slug/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/onboarding'
    | '/menu/$slug'
    | '/dashboard/categories'
    | '/dashboard/products'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/dashboard'
    | '/menu/$slug/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/menu/$slug'
    | '/_authenticated/dashboard/categories'
    | '/_authenticated/dashboard/products'
    | '/_authenticated/dashboard/qr'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/menu/$slug/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  MenuSlugRoute: typeof MenuSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/qr': {
      id: '/_authenticated/dashboard/qr'
      path: '/qr'
      fullPath: '/dashboard/qr'
      preLoaderRoute: typeof AuthenticatedDashboardQrRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/products': {
      id: '/_authenticated/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof AuthenticatedDashboardProductsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categories': {
      id: '/_authenticated/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof AuthenticatedDashboardCategoriesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/menu/$slug/product/$productId': {
      id: '/menu/$slug/product/$productId'
      path: '/product/$productId'
      fullPath: '/menu/$slug/product/$productId'
      preLoaderRoute: typeof MenuSlugProductProductIdRouteImport
      parentRoute: typeof MenuSlugRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardCategoriesRoute: typeof AuthenticatedDashboardCategoriesRoute
  AuthenticatedDashboardProductsRoute: typeof AuthenticatedDashboardProductsRoute
  AuthenticatedDashboardQrRoute: typeof AuthenticatedDashboardQrRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardCategoriesRoute:
      AuthenticatedDashboardCategoriesRoute,
    AuthenticatedDashboardProductsRoute: AuthenticatedDashboardProductsRoute,
    AuthenticatedDashboardQrRoute: AuthenticatedDashboardQrRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MenuSlugRouteChildren {
  MenuSlugProductProductIdRoute: typeof MenuSlugProductProductIdRoute
}

const MenuSlugRouteChildren: MenuSlugRouteChildren = {
  MenuSlugProductProductIdRoute: MenuSlugProductProductIdRoute,
}

const MenuSlugRouteWithChildren = MenuSlugRoute._addFileChildren(
  MenuSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  MenuSlugRoute: MenuSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
